/*
 * generated by Xtext
 */
package org.shashwat.xtext.smallJava;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmallJavaDslRuntimeModule extends org.shashwat.xtext.smallJava.AbstractSmallJavaDslRuntimeModule {

}
