/*
 * generated by Xtext
 */
package org.shashwat.xtext.smallJava.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SmallJavaDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/shashwat/xtext/smallJava/parser/antlr/internal/InternalSmallJavaDsl.tokens");
	}
}
