/**
 * generated by Xtext
 */
package org.shashwat.xtext.smallJava.validation;

import org.shashwat.xtext.smallJava.validation.AbstractSmallJavaDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmallJavaDslValidator extends AbstractSmallJavaDslValidator {
}
